[theme]
primaryColor = "#8DC63F"
backgroundColor = "#071a1d"
secondaryBackgroundColor = "#0e2a2f"
textColor = "#f5f7fa"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
